# Generated by Django 5.0.3 on 2024-03-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataviewer', '0003_alter_csvdata_x_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='x_value',
            new_name='x_value_temp',
        ),
    ]
